### PR TITLE
Make defaults.reek only relevant as documentation

### PR DESCRIPTION
**Pull request by mvz**
This stops in-development configuration changes interfering with running external versions of Reek. Case in point: CodeClimate.

### CODE REVIEW

**Comment by mvz** [comment]
Nope, that didn't help.

**Comment by mvz** [comment]
I still think this is a good change, though.

**Comment by mvz** [comment]
It gets weirder and weirder since I can run codeclimate's reek engine just fine locally.

**Comment by mvz** [comment]
Hm. It seems #1345 broke this.The check is relevant if no configuration file can be found at all.

**Comment by troessner** [comment]
Change looks good to me as well but travis disagrees as well ;)

**Comment by troessner** [comment]
Cant merge on my phone cause the build is failing because of CC. This is getting annoying. Lets quickly fix our CC integration or kill it.

**Comment by mvz** [comment]
Ok, I'll merge this from here and see if that helps.

**Comment by mvz** [comment]
I think that fixed it: https://codeclimate.com/github/troessner/reek/builds

**Comment by troessner** [comment]
Awesome!

**Pull request merged**
