### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by gogainda**

### CODE REVIEW

**Comment by mvz** [comment]
This PR doesn't make much sense :confused:

**Comment by mvz** [comment]
@gogainda after looking at your other recent pull requests, I see what you're trying to do here. But open source maintainers shoudn't have to go hunting for this. Since you're filing a lot of these, consider making a standard text to put in these pull requests to explain the purpose.

**Comment by gogainda** [comment]
Usually I close such pr when I see that build is failing. In that case tests are passing but code cov is different for truffleruby so it failed

**Comment by mvz** [comment]
You're still alerting all the maintainers with your test. You can also run the tests on your own machine.

**Pull request closed without merging**
