### PR TITLE
Match absolute paths of directories in .reek.yml

### PR DESCRIPTION
**Pull request by maximpertsov**
Proposed solution to address https://github.com/troessner/reek/issues/1540

### CODE REVIEW

**Comment by mvz** [comment]
Thanks, @maximpertsov, that looks like a good solution.

@troessner I think you know this part of the code best. Any thoughts?

**Comment by troessner** [comment]
I like it! Good to merge from my side, let's go ;)

**Comment by troessner** [comment]
Thanks @maximpertsov !

**Comment by troessner** [comment]
And released it is! 

> Pushed reek 6.0.1 to rubygems.org

**Pull request merged**
