### PR TITLE
Rename `CodeParser` to `TreeWalker`.

### PR DESCRIPTION
**Pull request by troessner**

### CODE REVIEW

**Comment by troessner** [comment]
Like discussed in #395

**Comment by mvz** [comment]
Busted by RuboCop!

**Comment by mvz** [comment]
The changes are fine though; I think you only need to rename the file mentioned in `.rubocop.yml`.

**Comment by troessner** [comment]
Fixed!.:)

**Comment by chastell** [comment]
The changes also look good to me; should I merge in such cases?

Also, what’s the Reek release policy? I’d very much welcome 2.0.1 (which would include the fix for #397). ;)

**Comment by troessner** [comment]
@chastell the policy is that every contributor can merge if the PR looks good to him, so please go ahead.
I can release 2.0.1 tonight.;)

**Comment by troessner** [comment]
No valiance here @chastell ? .;)
@mvz merge?

**Comment by chastell** [comment]
Argh, apologies, email management FUBAR resulting in me missing these replies. Thanks for merging and do feel free to roll 2.0.1 at will. ;)

**Pull request merged**
