### PR TITLE
Handle UTF-8 files in all locales

### LINKED ISSUE #1254: Error when run in POSIX locale
Hi, I just found a weird bug.

I have a local Docker for my project and `rubycritic` was not running on them, but it is running fine in the gitlab-ci.

Digging a little bit I found that gitlab-ci uses the `ruby:2.4-alpine` image and the local Dockerfile was using `ruby:2.4.1` image.

Searching for this kind of bug I found this issue whitesmith/rubycritic/issues/244 and here I'm to give you some evidences:

```
$ docker run -it ruby:2.4.1 bash
root@fac826472069:/# gem install reek
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
Fetching: descendants_tracker-0.0.4.gem (100%)
Successfully installed descendants_tracker-0.0.4
Fetching: equalizer-0.0.11.gem (100%)
Successfully installed equalizer-0.0.11
Fetching: coercible-1.0.0.gem (100%)
Successfully installed coercible-1.0.0
Fetching: ice_nine-0.11.2.gem (100%)
Successfully installed ice_nine-0.11.2
Fetching: axiom-types-0.1.1.gem (100%)
Successfully installed axiom-types-0.1.1
Fetching: virtus-1.0.5.gem (100%)
Successfully installed virtus-1.0.5
Fetching: codeclimate-engine-rb-0.4.0.gem (100%)
Successfully installed codeclimate-engine-rb-0.4.0
Fetching: ast-2.3.0.gem (100%)
Successfully installed ast-2.3.0
Fetching: parser-2.4.0.0.gem (100%)
Successfully installed parser-2.4.0.0
Fetching: rainbow-2.2.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.2
Fetching: reek-4.7.2.gem (100%)
Successfully installed reek-4.7.2
12 gems installed
root@fac826472069:/# reek
Inspecting 2440 file(s):
SS.S..S.S.S...S.S......SS..S..........................................SSSSS.SS..SS..SSS.SSSSSSSSS..SSS...................................................................................S......S......S.........S..S...S.................S..............S.SSSS..SSSSSSSSSS..SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..S..SS.SSSSSSSSSSSSSSSSSSS.SSSSSSS.S.S.....S.SSSS.S.................................................................................................................................SS.SSSSSSSSS...../usr/local/bundle/gems/parser-2.4.0.0/lib/parser/source/buffer.rb:164:in `source=': invalid byte sequence in US-ASCII (EncodingError)
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:99:in `parse'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:33:in `initialize'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:50:in `new'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:50:in `from'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/examiner.rb:40:in `initialize'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:26:in `new'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:26:in `block in populate_reporter_with_smells'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `each'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `populate_reporter_with_smells'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:17:in `execute'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/application.rb:29:in `execute'
	from /usr/local/bundle/gems/reek-4.7.2/bin/reek:14:in `<top (required)>'
	from /usr/local/bundle/bin/reek:23:in `load'
	from /usr/local/bundle/bin/reek:23:in `<main>'
```

The same test using other image works fine:

```
$ docker run -it ruby:2.4-alpine ash
/ # gem install reek
Fetching: thread_safe-0.3.6.gem (100%)
Successfully installed thread_safe-0.3.6
Fetching: descendants_tracker-0.0.4.gem (100%)
Successfully installed descendants_tracker-0.0.4
Fetching: equalizer-0.0.11.gem (100%)
Successfully installed equalizer-0.0.11
Fetching: coercible-1.0.0.gem (100%)
Successfully installed coercible-1.0.0
Fetching: ice_nine-0.11.2.gem (100%)
Successfully installed ice_nine-0.11.2
Fetching: axiom-types-0.1.1.gem (100%)
Successfully installed axiom-types-0.1.1
Fetching: virtus-1.0.5.gem (100%)
Successfully installed virtus-1.0.5
Fetching: codeclimate-engine-rb-0.4.0.gem (100%)
Successfully installed codeclimate-engine-rb-0.4.0
Fetching: ast-2.3.0.gem (100%)
Successfully installed ast-2.3.0
Fetching: parser-2.4.0.0.gem (100%)
Successfully installed parser-2.4.0.0
Fetching: rainbow-2.2.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.2
Fetching: reek-4.7.2.gem (100%)
Successfully installed reek-4.7.2
12 gems installed
/ # reek
Inspecting 2433 file(s):
SS.S..S.S.S...S.S......SS..S..........................................SSSSS.SS..SS..SSS.SSSSSSSSS..SSS...................................................................................S......S......S.........S..S...S.................S..............S.SSSS..SSSSSSSSSS..SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..S..SS.SSSSSSSSSSSSSSSSSSS.SSSSSSS.S.S.....S.SSSS.S.................................................................................................................................SS.SSSSSSSSS..................S......................................................
```
Reek will run fine and will report some issues with others gems, but it will run fine until the end. 

Good luck and thank you for the reek

### PR DESCRIPTION
**Pull request by mvz**
Fixes #1254.

### CODE REVIEW

**Comment by troessner** [comment]
Very cool!

**Comment by troessner** [comment]
@mvz i am still in Marocco, care for a new Reek and docker release?

**Comment by mvz** [comment]
Yes, I'll make a new release.

**Comment by mvz** [comment]
Not sure what docker release you're talking about?

**Pull request merged**
