### PR TITLE
Update parser dependency to the 3.3.x series

### PR DESCRIPTION
**Pull request by mvz**

### CODE REVIEW

**Review by troessner — APPROVED** [review]

**Comment by mvz** [comment]
@bkuhlmann I'll see if I can push out an update this weekend.

**Comment by troessner** [comment]
I took the liberty of doing that @mvz  ;)
-> #1767

**Comment by troessner** [comment]
Published @bkuhlmann

**Comment by mvz** [comment]
Thanks, @troessner!

**Pull request merged**
