### PR TITLE
Bump version to 3.11.

### PR DESCRIPTION
**Pull request by troessner**

### CODE REVIEW

**Comment by troessner** [comment]
and released it is!

**Comment by mvz** [comment]
I think it's better to always include the micro version (i.e., 3.11.0 in this case).

**Comment by mvz** [comment]
Other than that: \o/

**Comment by troessner** [comment]
I dont find that helpful, but i'll include it next time we have a *.*.0 version :)

**Comment by mvz** [comment]
Hm .. maybe I should investigate how bundler and rubygems deal with 3.11 vs 3.11.0. That way I'll have more than a hunch to back up my assertions :smile:

**Comment by troessner** [comment]
I always thought the .0 was implicit for bundler / rubygems. Hopefully  i am right :D

**Comment by mvz** [comment]
> Hopefully i am right :D

Turns out that yes, you are indeed right :laughing:.

**Comment by troessner** [comment]
Huzzaaaaaahhhh!

**Pull request merged**
