### PR TITLE
Isolate code climate dependency

### LINKED ISSUE #1507: [Defect] Remove codeclimate from runtime_dependency.
`codeclimate-engine-rb` **pull many gems**, but i have tested, those gem never used when i run reek command from a command line interface.

Infact, no this gem, reek can run successful on command line. (after comment several line of code for codeclimate/xml format),  do we consider add code make codeclimate acts as can plugged gem? 

Same issue as REXML gem.

Thank you!

### PR DESCRIPTION
**Pull request by mvz**
Fixes #1507.

### CODE REVIEW

**Comment by troessner** [comment]
Code looks good to me but travis disagrees :)

**Comment by mvz** [comment]
@troessner this is technically a breaking change. Shall we release this as part of reek 6? If so, I'd like to at least drop support for Ruby 2.3 at the same time.

**Comment by troessner** [comment]
This sounds like a great idea :)

**Comment by mvz** [comment]
Alright! I've opened #1509 for that.

**Pull request merged**
