### PR TITLE
Don't fiddle with rubygems or bundler

### PR DESCRIPTION
**Pull request by mvz**
We all love random build failures :heart:

### CODE REVIEW

**Comment by mvz** [comment]
Of course the set of failures is exactly the complement of master. What else did I expect?

**Comment by mvz** [comment]
OK:

* Re-install bundler: everything but 2.5 fails
* Don't re-install bundler: Only 2.5 fails

**Comment by tibbon** [comment]
I wonder if contacting Travis might help. I've had CI companies do a pretty good job at helping out with weird build issues like this.

**Comment by mvz** [comment]
See https://github.com/travis-ci/travis-ci/issues/9333

**Comment by mvz** [comment]
Fixed by TravisCI: https://github.com/travis-ci/travis-ci/issues/8969#issuecomment-390330259 :heart:

**Comment by mvz** [comment]
After this is merged, the other PRs can be rebased.

**Pull request merged**
