### PR TITLE
Remove annoying "@api private" comments.

### PR DESCRIPTION
**Pull request by troessner**

### CODE REVIEW

**Comment by troessner** [comment]
fixes #675

**Comment by troessner** [comment]
travis fails because of a rubocop update, fix up in #679

**Comment by chastell** [comment]
I merged the other PR, but I’d rather @mvz makes a call on this one – I’m not sure what the `@api private` was for but I think we used this in YARD?

**Comment by mvz** [comment]
> I’m not sure what the `@api private` was for but I think we used this in YARD?

Correct. I'm still planning to research an alternative solution (basically, where we mark what's public instead.

**Comment by mvz** [comment]
TL;DR: I'll create a PR for the solution I proposed in #578, but this can be merged in the mean time once it's green.

**Comment by troessner** [comment]
Something is really f**ked up with our rubocop set up:

>> lib/reek/ast/object_refs.rb:4:3: C: Style/Documentation: Missing top-level module documentation comment.
  module AST
  ^^^^^^

But I can't reproduce this locally, neither with the version that is in our gemspec nor with the latest version online. Grrarrrrrr.

**Comment by chastell** [comment]
I can replicate this with RuboCop 0.33.0 – what would be a good comment for `Reek::AST`? :)

**Comment by troessner** [comment]
>> I can replicate this with RuboCop 0.33.0 – what would be a good comment for Reek::AST? :)

Super weird. I can reproduce this now as well, but only on my new mac, not my old. WTF. 
Let me retry.

**Comment by troessner** [comment]
Green! LGTM? ;)

**Comment by mvz** [comment]
:+1:

**Pull request merged**
