### PR TITLE
Update rubocop to version 0.44.1 and autocorrect offenses

### PR DESCRIPTION
**Pull request by mvz**

### CODE REVIEW

**Comment by mvz** [comment]
I used my fork of [bundler-auto-update](https://github.com/pcreux/bundler-auto-update) for this. This could become a very useful tool.

**Comment by troessner** [comment]
>> I used my fork of bundler-auto-update for this. This could become a very useful tool.

Interesting indeed! Whats keeping us from integrating it now?

**Comment by mvz** [comment]
> Whats keeping us from integrating it now?

* My changes have not been accepted and released yet.
* It's pretty slow so probably best to only run it when you have time.
* It doesn't handle dependencies in gemspecs yet.
* Probably more I haven't found out about yet.

I'm basically experimenting with it on my on projects and fixing what I find.

**Comment by troessner** [comment]
Understood, then let's wait ;)

**Comment by Drenmi** [comment]
We use [Deppbot](https://www.deppbot.com/) at work. It is free for public repos, and will send you pull requests like this one:

screen shot 2016-10-24 at 15 19 27

*Disclaimer: I know the creator of Deppbot personally.*

**Comment by mvz** [comment]
@Drenmi we looked at Deppbot before, but it didn't quite do what we want at the time: #952.

**Comment by Drenmi** [comment]
@mvz: Ah! Thanks for pointing me to the issue. I vaguely recall hearing this before, now. 😀

**Pull request merged**
