### PR TITLE
Upgraded parser dependency

### PR DESCRIPTION
**Pull request by jasnow**
Upgraded parser dependency so it supports the latest version.

### CODE REVIEW

**Comment by troessner** [comment]
Hmmm, instead of 

>> s.add_runtime_dependency 'parser',                '<= 2.6', '>= 2.5.0.0', '!= 2.5.1.1'

how about doing

>> s.add_runtime_dependency 'parser',                '~> 2.6.0'

right away?

**Comment by troessner** [comment]
Looks good to me, @mvz what are your thoughts on this?

**Comment by mvz** [comment]
Thinking about this a bit more, I think it makes sense to keep allowing older Parser versions.

We could opt for `'< 2.7', '>= 2.5.0.0', '!= 2.5.1.1'`.

**Comment by troessner** [comment]
Ok, makes sense to me.

**Comment by jasnow** [comment]
@mvz, @troessner - done

**Comment by troessner** [comment]
Merged, thanks @jasnow !

**Comment by jasnow** [comment]
U R welcome - FYI: "bundle outdated" shows gems needing TLC.

**Comment by Drenmi** [comment]
> Thinking about this a bit more, I think it makes sense to keep allowing older Parser versions.

@mvz What was the main reason for settling on this? Asking because I need to make the same change in RuboCop. 😬

**Comment by mvz** [comment]
> What was the main reason for settling on this?

I'd like to not force an update of Parser for any current users of Reek.

**Comment by mvz** [comment]
> gems needing TLC

Most of those are not updateable at the moment, in particular the cucumber-related ones.

**Comment by jasnow** [comment]
@mvz - Thanks for the response - back into my hole - cheers.

**Comment by paul** [comment]
Any chance of a new release soon to include this? Our project emits this warning every time the server is started or a script is run, and we can't update parser until a new release of reek is made.

```
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.0-dev-compliant syntax, but you are running 2.6.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```

Thanks!

**Comment by troessner** [comment]
Just released v5.3.1. with this change included @paul ;)

**Pull request merged**
