### PR TITLE
Prepare 3.3.1 release.

### PR DESCRIPTION
**Pull request by troessner**
Quick review would be appreciated @mvz && @chastell  - i'd then release right away.

### CODE REVIEW

**Comment by troessner** [comment]
Merging this one on my own. Sorry, but I believe this is an important bug fix and we should release it a.s.a.p. and break our normal "do not merge yourself" protocol.

**Comment by backus** [comment]
Thanks for fixing this so quickly!

**Comment by troessner** [comment]
And reek 3.3.1 is released, please upgrade ;)

**Comment by chastell** [comment]
:+1:

**Comment by mvz** [comment]
:+1:

**Pull request merged**
