### PR TITLE
Move wiki pages to /docs.

### PR DESCRIPTION
**Pull request by troessner**

### CODE REVIEW

**Comment by troessner** [comment]
Ready for review!

What I did:

```Bash
 cp ../reek.wiki/*.md docs/
rm docs/Home.md more or less a duplicate to our README.md.
```

Then I ran the following script:

```Ruby
double_bracket_links = %r{
  \[\[
    (.*?)
  \]\]
}x

wiki_links = %r{
  (\(http.*?/(wiki)/.*?\))
}x

Pathname.glob(["README.md", "docs/*.md"]).each do |file|
  puts "Reading file #{file}..."
  copy = file.readlines
  copy.each do |line|
    line.gsub!(wiki_links) do |_hit|
      $1.gsub('wiki', 'docs')
    end

    line.gsub!(double_bracket_links) do |_hit|
      "[#{$1}](https://github.com/troessner/reek/docs/#{$1.gsub(' ', '-')})"
    end
  end
  file.write copy.join
end
```

**Comment by chastell** [comment]
The `https://github.com/troessner/reek/docs/Code-Smells` links do not work (no branch in the URL, the dash should be a space and the extension is missing). :)

Can you make them relative – just `docs/Code Smells.md` – so that they’re always from the same branch as the given README version?

**Comment by troessner** [comment]
>> The https://github.com/troessner/reek/docs/Code-Smells links do not work (no branch in the URL, the dash should be a space and the extension is missing). :)

Whoopsie! Of course I hadn't tested those links once. Shame on me. Thanks for catching this.:)

>> Can you make them relative – just docs/Code Smells.md – so that they’re always from the same branch as the given README version?

Done, I also removed all whitespace from the filenames - please see the updated comment above for what I did.
Should now be ready to, uhm, re-review..:)

**Comment by mvz** [comment]
I'm missing the name of the smell at the top of each file. The wiki uses the name of the file to display a heading, but this won't happen for the files in `doc/`.

**Comment by troessner** [comment]
@mvz updated accordingly. Anything else from your side or can we merge this?

**Comment by mvz** [comment]
Good to merge!

**Comment by mvz** [comment]
@troessner I just noticed this includes **all** wiki pages. Was that you intention? I think some parts of the wiki may be more suited to being updated gradually by users, while others make more sense as true core Reek documentation.

**Comment by troessner** [comment]
>> Was that you intention? 

Yes!

>> I think some parts of the wiki may be more suited to being updated gradually by users,

A quick check on our wiki's git history tells me that almost no user ever bothered to edit our wiki.
I'd rather keep this information in our repo. If a user wants to update this, it's so easy to create a PR nowadays that I can hardly think of this as a problem.

**Pull request merged**
