### PR TITLE
Improve change log

### PR DESCRIPTION
**Pull request by mvz**
- Format with markdown
- Add items for 3.0.4
- Add unreleased section
- Add date for each release
- Add entries for version 1.5.1

Inspired by http://keepachangelog.com/

### CODE REVIEW

**Comment by mvz** [comment]
I see there are still some misformats with nested lists. I'll fix those.

**Comment by mvz** [comment]
I rebased this.

Any thoughts?

**Comment by mvz** [comment]
Oh, wait, I didn't do this bit yet:
> I see there are still some misformats with nested lists. I'll fix those.

**Comment by mvz** [comment]
And done.

**Comment by chastell** [comment]
Looks good, merging!

How do we maintain this? Review the diff on each release?

**Comment by mvz** [comment]
We can add changes as we progress to the next release by putting them in the Unreleased section.

**Pull request merged**
