### PR TITLE
[WIP] Refactor ControlParameter.

### PR DESCRIPTION
**Pull request by troessner**
Prerequisite for #1386

### CODE REVIEW

**Comment by mvz** [comment]
Why do you want to move these classes to separate files? Fixing #1386 may mean changing the entire algorithm.

**Comment by troessner** [comment]
>> Why do you want to move these classes to separate files?

Because I'm lost in that jungle of odd inner classes and following "Make the change easy, then make the change" I want to increase readability and maintainability first.

>> Fixing #1381 may mean changing the entire algorithm.

If that happens, I'm perfectly fine with it ;)

**Comment by mvz** [comment]
> Make the change easy, then make the change

Ok, how about making this the first commit of the PR that fixes #1381?

**Comment by troessner** [comment]
>> Ok, how about making this the first commit of the PR that fixes #1381?

Ok, fair enough, I'll update my PRs ;)

**Comment by troessner** [comment]
Closing this in favor of #1386

**Pull request closed without merging**
