### PR TITLE
Fix a bunch of smells.

### PR DESCRIPTION
**Pull request by troessner**
Ladies and gentlemen,

may I present to you the ultimate "Make reek smell-free" pull request!

This little honeybadger you see below is still in its infancy but fixes already a dozen warnings (or disables them rightfully).

I won't stop till I drop and then we can finally use "rake test:quality" on travis!

### CODE REVIEW

**Comment by troessner** [comment]
Wanting to fix all smells in one PR was a bad plan as I now realize.

Way smarter: step by step.

So here's the first PR in an series ;)

Review please!

**Comment by chastell** [comment]
I used to put exceptions in a `.reek` file, but recently started moving them to code comments – this way (a) they move along with the method and (b) we could eventually make reek smell-free with the default config.

Also, rather than excluding DuplicateMethodCall I add a count, so that when it goes over the method is smelly again.

**Comment by chastell** [comment]
LGTM otherwise. :)

**Comment by troessner** [comment]
>> I used to put exceptions in a .reek file, but recently started moving them to code comments – this way (a) they move along with the method and (b) we could eventually make reek smell-free with the default config.

Good point! I removed the reek config again and added comments accordingly.

>> Also, rather than excluding DuplicateMethodCall I add a count, so that when it g oes over the method is smelly again.

Added!

**Comment by troessner** [comment]
Please re-review.;)

**Comment by chastell** [comment]
Ausgezeichnet!

**Pull request merged**
