### PR TITLE
Support Ruby 2.2

### PR DESCRIPTION
**Pull request by mvz**
- Add 2.2 to the Travis CI configuration
- Fix warnings
- Depend on unparser version that supports all relevant rubies

(#357).

### CODE REVIEW

**Comment by sauliusgrigaitis** [comment]
I get this stack trace after upgrading to Ruby 2.2.0 (both with this branch and with master).

home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:298:in `children': undefined method `children' for nil:NilClass (NoMethodError)
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:99:in `effective_body'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:89:in `dispatch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /home/saulius/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:498:in `run'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:149:in `block in emit_hash_body'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:184:in `parentheses'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:147:in `emit_hash_body'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:136:in `dispatch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /home/saulius/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:212:in `block in visit'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:242:in `conditional_parentheses'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:211:in `visit'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:23:in `block in emit_value'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:242:in `conditional_parentheses'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:22:in `emit_value'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:65:in `dispatch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /home/saulius/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:212:in `block in visit'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:242:in `conditional_parentheses'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:211:in `visit'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:284:in `call'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:284:in `delimited'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/literal/hash.rb:89:in `dispatch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /home/saulius/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:198:in `visit_plain'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:284:in `call'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:284:in `delimited'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:268:in `delimited_plain'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/send/arguments.rb:21:in `block in dispatch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:184:in `parentheses'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/send/arguments.rb:20:in `dispatch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /home/saulius/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:498:in `run'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/send.rb:187:in `emit_arguments'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/send/regular.rb:21:in `dispatch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /home/saulius/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter/send.rb:32:in `dispatch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser/emitter.rb:103:in `write_to_buffer'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `call'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:117:in `block (3 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:63:in `block (3 levels) in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:62:in `block (2 levels) in fetch'
	from /home/saulius/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:61:in `block in fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/thread_safe-0.3.4/lib/thread_safe/cache.rb:58:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/memory.rb:60:in `fetch'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/memoizable-0.4.2/lib/memoizable/method_builder.rb:116:in `block (2 levels) in create_memoized_method'
	from /home/saulius/.rvm/gems/ruby-2.2.0/gems/unparser-0.1.16/lib/unparser.rb:31:in `unparse'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/source/sexp_formatter.rb:13:in `format'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/source/sexp_node.rb:75:in `format_ruby'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/smells/duplicate_method_call.rb:73:in `call'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/smells/duplicate_method_call.rb:98:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/smells/duplicate_method_call.rb:98:in `sort_by'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/smells/duplicate_method_call.rb:98:in `calls'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/smells/duplicate_method_call.rb:102:in `smelly_calls'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/smells/duplicate_method_call.rb:52:in `examine_context'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/smells/smell_detector.rb:89:in `examine'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/smell_repository.rb:59:in `block in examine'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/smell_repository.rb:58:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/smell_repository.rb:58:in `examine'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:161:in `check_smells'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:155:in `block in inside_new_context'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:167:in `push'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:153:in `inside_new_context'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:41:in `process_def'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:24:in `process'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `block in process_default'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `process_default'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:93:in `process_begin'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:24:in `process'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `block in process_default'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `process_default'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:34:in `block in process_module'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:154:in `block in inside_new_context'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:167:in `push'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:153:in `inside_new_context'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:33:in `process_module'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:24:in `process'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `block in process_default'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `process_default'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:34:in `block in process_module'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:154:in `block in inside_new_context'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:167:in `push'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:153:in `inside_new_context'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:33:in `process_module'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:24:in `process'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `block in process_default'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:29:in `process_default'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:34:in `block in process_module'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:154:in `block in inside_new_context'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:167:in `push'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:153:in `inside_new_context'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:33:in `process_module'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/code_parser.rb:24:in `process'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/core/sniffer.rb:20:in `report_on'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/examiner.rb:41:in `block in initialize'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/source/source_repository.rb:41:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/source/source_repository.rb:41:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/examiner.rb:39:in `initialize'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/cli/reek_command.rb:13:in `new'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/cli/reek_command.rb:13:in `block in execute'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/cli/reek_command.rb:12:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/cli/reek_command.rb:12:in `execute'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/lib/reek/cli/application.rb:32:in `execute'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-29722b816369/bin/reek:11:in `<top (required)>'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bin/reek:23:in `load'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bin/reek:23:in `<main>'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by mvz** [comment]
@sauliusgrigaitis that's the same problem that is causing the tests to fail. It is a problem in the unparser gem we use. Once https://github.com/mbj/unparser/issues/33 is fixed, reek can support CRuby 2.2.0.

**Comment by sauliusgrigaitis** [comment]
@mvz thanks, I can confirm that your unparser ```ruby-22``` branch works!

**Comment by mvz** [comment]
@sauliusgrigaitis thanks, I hadn't actually checked that yet.

**Comment by mvz** [comment]
I'm going to try a nasty trick to get this passing on Travis.

**Comment by mvz** [comment]
No nasty tricks needed.

**Comment by mvz** [comment]
And it's green. @troessner can you merge this?

**Comment by troessner** [comment]
Merged!.:)

**Comment by troessner** [comment]
And 1.6.3 is released!

**Pull request merged**
