### PR TITLE
Improve "How reek works".

### PR DESCRIPTION
**Pull request by troessner**

### CODE REVIEW

**Comment by mvz** [comment]
These Travis failures are due to a problem on `develop`. I don't have time to look into that right now, but we'll need to fix it before merging any other pull requests. I may be able to look at it tomorrow evening.

**Comment by chastell** [comment]
@troessner Have you considered using Graphviz for this (and generate the graph from a Dot file)? I had it at the back of my head when I first looked into `reek`, then proposed this as a task for ROSSConf (but no-one picked this up), then forgot…

**Comment by troessner** [comment]
>> @troessner Have you considered using Graphviz for this (and generate the graph from a Dot file)?

I did and I believe that all those tools suck and I'm a gazillion times faster with Ascii art.:)
Do you see a concrete benefit right now?

**Comment by mvz** [comment]
> I'm a gazillion times faster with Ascii art

Do you use any special tools for editing ascii art?

**Comment by chastell** [comment]
I hope a Graphviz graph would be more readable than the ASCII art one, but I’ll come back with one (mid-June at the earliest, though, sorry) and we can discuss further. :)

**Comment by troessner** [comment]
>> Do you use any special tools for editing ascii art?

Yes, my vi.:D

>> I hope a Graphviz graph would be more readable than the ASCII art one, but I’ll come back with one (mid-June at the earliest, though, sorry) and we can discuss further. :)

I'm absolutely open for using a tool as well if that makes it easier for us as a team.

**Comment by chastell** [comment]
:+1:

**Pull request merged**
