### PR TITLE
UnusedPrivateMethod to be detect use of methods via `Method#to_proc`

### PR DESCRIPTION
**Pull request by ydah**
Fixes https://github.com/troessner/reek/issues/1515:

### CODE REVIEW

**Comment by troessner** [comment]
Looks good to me! @mvz wdyt?

**Comment by mvz** [comment]
Yes, looks good.

**Comment by troessner** [comment]
Merged, thanks @ydah !

**Comment by troessner** [comment]
And I just released version 6.1.1 with your fix in it @ydah !

**Comment by ydah** [comment]
@troessner @mvz Thank you so much!

**Pull request merged**
