### PR TITLE
Improve README: Update tools, integrations and authors.

### PR DESCRIPTION
**Pull request by troessner**
Also fixes https://github.com/troessner/reek/issues/624

### CODE REVIEW

**Comment by mvz** [comment]
Looks good.

Maybe you can also update the bit about using reek with Rails?

**Comment by troessner** [comment]
>> Maybe you can also update the bit about using reek with Rails?

What do you mean?

What would you update here: https://github.com/troessner/reek#working-with-rails ?

**Comment by mvz** [comment]
Oh I see .. something weird is going on in the diff there. It still shows the line "We plan to improve Reek in the near future so that it plays better with Rails."

**Comment by troessner** [comment]
I dont see that in the diff. Maybe some weird css issue? Maybe clean your Browser cache?

**Comment by mvz** [comment]
I'm seeing it in the diff locally as well, and I just updated all branches from the GitHub repo. I can see that this branch is based on a commit just before we merged in Rails mode. Perhaps you rebased but didn't push yet?

**Comment by troessner** [comment]
>> I'm seeing it in the diff locally as well, and I just updated all branches from the GitHub repo. I can see that this branch is based on a commit just before we merged in Rails mode. Perhaps you rebased but didn't push yet?

Not sure what happened there, so I resorted to my favourite git move when things dont work out: Create a new branch!
And voila: https://github.com/troessner/reek/pull/635
AFAIS the history looks clean.
Closing this one.

**Pull request closed without merging**
