### PR TITLE
Prepare 3.5.0 release.

### PR DESCRIPTION
**Pull request by troessner**

### CODE REVIEW

**Comment by chastell** [comment]
:shipit:

**Comment by troessner** [comment]
@chastell care to release as well? 

I think the person merging should be the one releasing so we have a clear workflow.
WDYT @chastell @mvz?

**Comment by chastell** [comment]
Released! I agree that the ‘merge + release’ workflow is one less ping-pong.

**Comment by mvz** [comment]
Yes, sounds reasonable.

**Pull request merged**
