### PR TITLE
Update TooManyMethods default value to 15.

### LINKED ISSUE #641: TooManyMethods's slightly insane default value
After https://github.com/troessner/reek/pull/634 I got curios what other **insane** default values we might have in reek and I found this bomb: https://github.com/troessner/reek/blob/master/lib/reek/smells/too_many_methods.rb#L21

25. Well, no wonder that smell was never reported in any code I have ever seen.

I'd vote for 10 methods max. WDYT?

### PR DESCRIPTION
**Pull request by troessner**
Fixes #641

### CODE REVIEW

**Comment by troessner** [comment]
```
Failures:
  1) Reek::Smells::FeatureEnvy should report highest affinity
     Failure/Error: expect(src).to reek_of(:FeatureEnvy, name: 'total')
     NoMethodError:
       undefined method `warnings' on nil:NilClass.
     # kernel/delta/kernel.rb:78:in `warnings (method_missing)'
     # ./lib/reek/examiner.rb:49:in `smells'
     # ./lib/reek/spec/should_reek_of.rb:21:in `matches?'
     # ./spec/reek/smells/feature_envy_spec.rb:92:in `__script__'
     # kernel/common/eval.rb:101:in `instance_exec'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/bootstrap/array.rb:97:in `map'
     # kernel/delta/code_loader.rb:66:in `load_script'
     # kernel/delta/code_loader.rb:152:in `load_script'
     # kernel/loader.rb:656:in `script'
     # kernel/loader.rb:842:in `main'
```

Ah, ok. Re-running.

**Comment by troessner** [comment]
And travis is green.:)

**Comment by chastell** [comment]
Was that a Rubinius failure? :)

Merging!

**Comment by troessner** [comment]
>> Was that a Rubinius failure? :)

:laughing:

**Comment by troessner** [comment]
Hmmm, i'd love to release a new version because of @HParker fix in #639 but this change here actually warrants minor version jump. PR incoming.

**Pull request merged**
