### PR TITLE
Add auto-generated change log file.

### PR DESCRIPTION
**Pull request by skywinder**
Hi, as I can see, you are carefully fill tags and labels for issues in your repo.

For such cases I create a [github_changelog_generator](https://github.com/skywinder/github-changelog-generator), that generate change log file based on **tags**, **issues** and merged **pull requests** from :octocat: Issue Tracker.

This PR add change log file to your repo (generated by this script).
You can check, how it is look like here: [Change Log](https://github.com/skywinder/reek/blob/add-change-log-file/CHANGELOG_AUTO.md)

Some essential features, that has this script:

-  it **exclude** not-related to changelog issues (any issue, that has label `question` `duplicate` `invalid` `wontfix` )
- Distinguish issues **according labels**:
    - Merged pull requests (all `merged` pull-requests)
    - Bug fixes (by label `bug` in issue)
    - Enhancements (by label `enhancement` in issue)
    -   Issues (closed issues `w/o any labels`)
- Generate neat Change Log file according basic [change log guidelines](http://keepachangelog.com).

You can easily update this file in future by simply run script: `github_changelog_generator troessner/reek` in your repo folder and it make your Change Log file up-to-date again!

Hope you find this commit as useful. :wink:

P.S.
I know that you already has CHANGELOG.md file but give this script a chance and compare it with yours change log. Hope, you will love it! :blush:

### CODE REVIEW

**Comment by skywinder** [comment]
As I can see your repo is well labeled and you are using custom labels. So I generate change log with some adjustments:
`github_changelog_generator troessner/reek --exclude-labels discussion,maybe-some-day --bug-labels defect,internal,smell --enhancement-labels feature`

Hope you find it useful and thanks for your cool project!

**Comment by troessner** [comment]
That's pretty cool I have to say. That's a more or less accurate history of reek as far as I can see.
:+1:  for merging.
@mvz @chastell WDYT?

**Comment by skywinder** [comment]
BDW, you can amend it to your manually-generated change log to auto-generated change log with `-b` option (https://github.com/skywinder/github-changelog-generator/pull/258)

**Comment by skywinder** [comment]
BDW, you can amend it to your manually-generated change log to auto-generated change log with `-b` option (https://github.com/skywinder/github-changelog-generator/pull/258)

**Comment by mvz** [comment]
This is very interesting. I have some questions:
* I suppose we we can play around with the tags on our issues to put them in the right categories?
* How can we get rid of issues that are closed without associated changes to the code? For example, I see #601 in there. Should we tag those wontfix?
* In our workflow, we often have an issue that reports a bug, and an associated pull request. How can we avoid both of them appearing?

**Comment by troessner** [comment]
@skywinder any updates on this?

**Comment by troessner** [comment]
Closing this since @skywinder appears inactive.

**Comment by skywinder** [comment]
@troessner was in vacation. Now I'm back and ready to participate.

---

@mvz 

> I suppose we we can play around with the tags on our issues to put them in the right categories?

Yes, but with labels, not tags. But most of all your issues already well-categorized. You can adjust command to move some labels in correct category:

    github_changelog_generator troessner/reek --exclude-labels discussion,maybe-some-day --bug-labels defect,internal,smell --enhancement-labels feature

---

> How can we get rid of issues that are closed without associated changes to the code? For example, I see #601 in there. Should we tag those `wontfix`?

Correct! :+1: Even if left `feature` label and add `wontfix` It will dissapear from change log.

---

> In our workflow, we often have an issue that reports a bug, and an associated pull request. How can we avoid both of them appearing?

Yes, I'm thinking about this case.
Please, check details in related issue: https://github.com/skywinder/github-changelog-generator/issues/67
I took some research (even write to @github support), but didn't  find way to link related issues and PR by Github API yet.

**Comment by skywinder** [comment]
`--base` option works, but I want to merge it in better manner.

    github_changelog_generator troessner/reek --exclude-labels discussion,maybe-some-day --bug-labels defect,internal,smell --enhancement-labels feature  -b CHANGELOG.md --since-tag v3.3.0

**Comment by skywinder** [comment]
I create special issue for your case: https://github.com/skywinder/github-changelog-generator/issues/269

Please hold this PR for a while.
If you have any suggestions, how to present manual and auto change logs - feel free to contact me.

**Comment by troessner** [comment]
@skywinder Closing this for now, please re-open when fixed on your side.

**Comment by skywinder** [comment]
Ok! I'm working on other projects for now. I will let you know, when it will be ready.

**Pull request closed without merging**
