### PR TITLE
Remove "develop" rake task.

### PR DESCRIPTION
**Pull request by troessner**
I believe nobody is using this anymore and we can get rid of it.

### CODE REVIEW

**Comment by mvz** [comment]
We do use this to keep `config/defaults.reek` in sync with reality. However, that file is never read so serves more as documentation. If we get rid of the task we should get rid of the file as well.

**Comment by troessner** [comment]
>> If we get rid of the task we  should get rid of the file as well.

Why? Why not leave it there as documentation?
For instance, I find it quite convenient and helpful to be able to link to this...

**Comment by mvz** [comment]
> Why not leave it there as documentation?

Sure, but then we should leave the task so the file is automatically updated when we change config defaults.

**Comment by troessner** [comment]
>> Sure, but then we should leave the task so the file is automatically updated when we change config defaults.

Good point..:)

-> Closed.

**Pull request closed without merging**
