### PR TITLE
Explain that smell messages are not part of our API.

### PR DESCRIPTION
**Pull request by troessner**
Hopefully this will save us some trouble in the future...

### CODE REVIEW

**Comment by mvz** [comment]
Nice, that's a good explanation. One possible addition: You could also mention the structured formats (YAML, JSON) as alternatives if people need to access reeks results in a more detailed way.

**Comment by troessner** [comment]
>> Nice, that's a good explanation. One possible addition: You could also mention the structured formats (YAML, JSON) as alternatives if people need to access reeks results in a more detailed way.

Good idea, I added a paragraph at the end of my changes.

**Comment by troessner** [comment]
Anybody merging this bad boy?

**Comment by chastell** [comment]
:+1: merging!

**Pull request merged**
