### PR TITLE
Handle new lambda syntax in NestedIterators

### LINKED ISSUE #947: Undefined method `name' for s(:lambda)
From https://github.com/troessner/reek/issues/942#issuecomment-226103640:

> this is also happening to me... was using an old version, upgraded to 4.0.4 and it stopped working; I can't determine what is triggering this...

> ```
⚡ reek
$HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:139:in `block in ignored_iterator?': undefined method `name' for s(:lambda)
:#<Class:0x000000059b7670> (NoMethodError)
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:139:in `any?'
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:139:in `ignored_iterator?'
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:130:in `increment_depth'
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:110:in `block in scout'
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:109:in `each'
        from $HOME/.rvm/gems/ruby-2.2.1/gems/reek-4.0.4/lib/reek/smells/nested_iterators.rb:109:in `flat_map'
```

### PR DESCRIPTION
**Pull request by mvz**
Fixes #947.

### CODE REVIEW

**Comment by mvz** [comment]
It looks like @nachokb and I fixed this at the same time :smile:.

**Comment by nachokb** [comment]
looking at your PR now I understand a little more about Reek

**Comment by troessner** [comment]
Very nice @mvz - merged!

**Comment by troessner** [comment]
@mvz are you gonna handle the release of 4.0.5?

**Comment by mvz** [comment]
Sure, I'll release tomorrow morning.

**Comment by troessner** [comment]
Just released 4.0.5!

**Pull request merged**
