### PR TITLE
Fix generating HTML report

### PR DESCRIPTION
**Pull request by guilhermesimoes**
Fix needed due to #346

### CODE REVIEW

**Comment by troessner** [comment]
Great! Thanks for that, merged.;)

**Comment by guilhermesimoes** [comment]
Yey, I got a commit into Reek! :dancer:

**Comment by mvz** [comment]
@troessner perhaps we need to patch 1.6 with this too?

**Comment by troessner** [comment]
Yes! I just released 1.6.6 with the fix.:)

**Pull request merged**
