### PR TITLE
Remove source rb

### PR DESCRIPTION
**Pull request by troessner**
....because it is unnecessary. And files should be required where they are used, we shouldn't just require all-the-things.:)

Branched off of #435 - let's get this one merged first.

### CODE REVIEW

**Comment by troessner** [comment]
Ready for review @mvz @chastell !.:)

**Comment by mvz** [comment]
I agree with this change in principle, but the builds are all failing :-).

**Comment by chastell** [comment]
Thanks for fixing, merged!

**Comment by troessner** [comment]
>> I agree with this change in principle, but the builds are all failing :-).

Whoopsie.:)

**Pull request merged**
