### PR TITLE
Tinycleanup

### PR DESCRIPTION
**Pull request by tuexss**
Small cleanup commit for more transparent help-output, moving external links http->https, and some minor typos/formatting issues.

### CODE REVIEW

**Comment by chastell** [comment]
Thanks! I couldn’t add commits to this PR to make the failing feature pass, so I reopened this as #415.

**Comment by tuexss** [comment]
hmm, can I change my settings somehow to allow others to do that?

**Comment by chastell** [comment]
To the best of my knowledge – unfortunately not. The only PRs that one can modify are PRs from branches one can write to (so I’d have to have write access to your fork of Reek).

**Comment by tuexss** [comment]
ok, I'd have to add you as collaborator manually on my fork. good to know, thanks!

**Pull request closed without merging**
