### PR TITLE
Remove cucumber annotations

### PR DESCRIPTION
**Pull request by mvz**
#373.

### CODE REVIEW

**Comment by troessner** [comment]
PR looks good but travis is failing big time.;)

**Comment by chastell** [comment]
Sorry for the thread necromancy (hi!), but weren’t `@ruby20` and `@ruby21` useful for skipping them on Ruby 1.9 and 2.0? Ah, maybe the parser gem parses new Ruby syntax just fine even when running under Ruby 1.9…

**Comment by mvz** [comment]
Yes, we explicitely use parser's ruby 2.1 parser to allow reek to parse the new syntax even on older rubies. We could move to 2.2 even.

**Comment by chastell** [comment]
Cool – and thanks for the explanation, that makes perfect sense.

**Pull request merged**
