### PR TITLE
Prepare version 5.3.0 for release

### PR DESCRIPTION
**Pull request by mvz**

### CODE REVIEW

**Comment by mvz** [comment]
Are we all in agreement that supporting a new version of Ruby is a feature-level change?

**Comment by troessner** [comment]
>> Are we all in agreement that supporting a new version of Ruby is a feature-level change?

Yes, works for me ;)

**Comment by troessner** [comment]
Pretty sure our cucumber features will fail in this PR ;)

**Comment by mvz** [comment]
> Pretty sure our cucumber features will fail in this PR ;)

Already fixed :-).

**Comment by mvz** [comment]
And released it is :tada:.

**Pull request merged**
