### PR TITLE
[WIP] Recognize singleton methods defined via module function.

### LINKED ISSUE #27: module_function does not disable Utility Function
A bit like a method on a class, the following should presumably not trigger Utility Function?

    module MyModule
      def reset!
        # ...
      end
      module_function :reset!
    end

### PR DESCRIPTION
**Pull request by troessner**
Please don't review yet, still tweaking things here and there.
Fixes #27

### CODE REVIEW

**Comment by troessner** [comment]
Ready for review!

**Comment by chastell** [comment]
Just did a cursory look for now, but does it handle the common (at least in my code) case where `module_function` is a scoping operator? The tests don’t cover this and I don’t think the implementation covers this either:

```Ruby
module Foo
  module_function

  def bar
    :bar
  end

  def baz
    :baz
  end
end

Foo.bar   #=> :bar
Foo.baz   #=> :baz
```

**Comment by chastell** [comment]
(I did a partial stab at this before, hoping I can use something like the `Smells::Attribute` tracking of its `VISIBILITY_MODIFIERS`, but didn’t have time to get with it very far.)

**Comment by troessner** [comment]
>> Just did a cursory look for now, but does it handle the common (at least in my code) case where module_function is a scoping modifier? The tests don’t cover this and I don’t think the implementation covers this either:

It doesn't! I knew I would miss a couple of cases.:)
I'll look into it.

**Comment by chastell** [comment]
Awsome. The trick is that the first bare `public`, `protected` or `private` after a bare `module_function` resets the following methods to not be `module_functions` anymore (unless another bare `module_function` happens, of course).

**Comment by mvz** [comment]
I think `Attribute` does some visibility tracking so you may want to take a look at that and perhaps extract common functionality.

**Comment by troessner** [comment]
Closing this one to re-open it against master.

**Pull request closed without merging**
