### PR TITLE
Fix Readme location of rspec matchers

### PR DESCRIPTION
**Pull request by tjchambers**

### CODE REVIEW

**Comment by mvz** [comment]
Hi @tjchambers, thanks for your pull request. Would you mind creating a branch for this and squashing your commits?

**Comment by troessner** [comment]
Fixed in https://github.com/troessner/reek/commit/8ebe1a9616b42cbe2c1d66cf00a0ed5b057fc27a
Unfortunately I couldn't use the "--author=..." switch for the commit since Tim doesn't exist as committer in the git history. I did mention it in the commit message though.

Closed, thanks!

**Comment by mvz** [comment]
@troessner directly cherry-picking @tjchambers' commit would probably have worked.

**Comment by troessner** [comment]
>> @troessner directly cherry-picking @tjchambers' commit would probably have worked.

Yes, of course! Sorry, next time.:)

**Comment by tjchambers** [comment]
Sorry - I got left out of this conversation as I didn't receive the first request to squash commits. Thanks for taking action on it though!

**Pull request closed without merging**
