### PR TITLE
Added instruction to use reek in ruby code

### PR DESCRIPTION
**Pull request by bibstha**
The file api.md inside docs folder contain instruction to run reek inside a ruby app.

### CODE REVIEW

**Comment by chastell** [comment]
Thanks!

@mvz / @troessner: I’m merging this as a good starting point for the discussion about what public API should we support for `reek` 3.0 (as in, if this hooks too deep then maybe we should have some good methods for this closer to the top of the namespace).

**Comment by troessner** [comment]
@bibstha thanks a lot!

@mvz @chastell 
By convention, this would have belonged in the wiki, not in the docs folder. But I still highly welcome this because I think we should discuss if  it wouldnt make sense to move everything in the wiki as well. 
IMO this is what we should do. The separation between code and "some" documentation and most of the other documentation in the wiki doesn't make much sense to me.

So I'd suggest moving everything we have in the wiki into the docs folder and then disable the github wiki. WDYT?

**Comment by chastell** [comment]
> I'd suggest moving everything we have in the wiki into the docs folder and then disable the github wiki

I would prefer to have the docs in the code for two reasons:
* as much as I like GitHub, I’m not a huge fan of being tied to it more than necessary/useful,
* smell examples in the repo could be checked with [Ataru](https://github.com/CodePadawans/ataru) whether they’ll still smelly (and whether the refactoring example removes the smell).

Given how wide the links to our wiki are distributed we should probably turn the wiki pages into stubs pointing to the new locations in the docs folder – _but_ this could be automated, as [the GitHub wiki itself is a Git repo](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/) in its own right (this might seem to invalidate the second point above, but I think it would be simpler to have the docs in the same repo as the rest of `reek` and just have a single CI job).

**Comment by troessner** [comment]
>> this might seem to invalidate the second point above, but I think it would be simpler to have the docs in the same repo as the rest of reek and just have a single CI job).

Yes, exactly.

**Pull request merged**
