### PR TITLE
Checking lambda should not raise error

### LINKED ISSUE #960: Checking lambda raises "undefined method `module_creation_call?`"
When running reek on a lambda set to a constant, the context builder raises a NoMethodError.

Example Code:

```
`MISSING_TRANSLATION_HANDLER = -> (exception, _locale, _key, _options) { raise exception.to_exception }`
```

Backtrace:

```
gems/reek-4.1.0/lib/reek/ast/sexp_extensions/module.rb:58:in `defines_module?': undefined method `module_creation_call?' for s(:lambda):#<Class:0x007f7fb8fc1248> (NoMethodError)
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/context_builder.rb:106:in `process_casgn'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/context_builder.rb:63:in `build'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/context_builder.rb:30:in `initialize'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/examiner.rb:80:in `new'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/examiner.rb:80:in `run'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/examiner.rb:37:in `initialize'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/cli/command/report_command.rb:24:in `new'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/cli/command/report_command.rb:24:in `block in populate_reporter_with_smells'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/cli/command/report_command.rb:23:in `each'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/cli/command/report_command.rb:23:in `populate_reporter_with_smells'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/cli/command/report_command.rb:15:in `execute'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/lib/reek/cli/application.rb:28:in `execute'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/gems/reek-4.1.0/bin/reek:13:in `<top (required)>'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/bin/reek:23:in `load'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/bin/reek:23:in `<main>'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/bin/ruby_executable_hooks:15:in `eval'
	from /Users/alex.gerstein/.rvm/gems/ruby-2.2.2@zenpayroll/bin/ruby_executable_hooks:15:in `<main>'
```

### PR DESCRIPTION
**Pull request by waldyr**
This fixes #960.

### CODE REVIEW

**Comment by troessner** [comment]
Love it! Pls make travis green and then I'll merge this bad boy right away including a release.

**Comment by mvz** [comment]
> Pls make travis green

activesupport DIAF! :fire: :fire: :no_good: :fire_engine:

**Comment by waldyr** [comment]
Could you please elaborate on how should I fix this?

**Comment by mvz** [comment]
Pinning activesupport to a version that works on all Reek's supported Ruby versions will probably work. I don't think it's a runtime dependency, so users of Reek should be ok. If it *is* a runtime dependency, we need to get rid of it.

**Comment by mvz** [comment]
(Technically, this has nothing to do with this pull request. I'm sure a rebuild of master will also fail at the moment.)

**Comment by troessner** [comment]
>>  I don't think it's a runtime dependency, so users of Reek should be ok.

It's in the Gemfile, we only use it in our specs.

Merging this bad boy!

**Comment by troessner** [comment]
And released it is, thanks @waldyr !

**Pull request merged**
