### PR TITLE
When detecting single smell, allow configuration for other smells

### PR DESCRIPTION
**Pull request by mvz**
#682.

### CODE REVIEW

**Comment by chastell** [comment]
Ok, so we currently raise when there is config for a _valid_ smell that’s not in the currently enabled ones; this is clearly wrong. But this seems to fix it by removing a feature that’s actually useful: having a config for an _invalid_, non-existing smell (e.g., because someone made a typo in the smell’s name).

I think this feature is useful; can we keep raising when encountering configuration for smells that don’t exist at all?

**Comment by mvz** [comment]
> can we keep raising when encountering configuration for smells that don’t exist at all?

We already raise earlier in the process when reading the configuration file from disk.

**Comment by mvz** [comment]
Due to the changes to master this is basically just an update of the cucumber scenarios now.

**Comment by troessner** [comment]
>> Due to the changes to master this is basically just an update of the cucumber scenarios now.

Then I believe we should another branch- and commit name for this, otherwise the history is going to be very confusing ;)

**Comment by mvz** [comment]
Agreed.

**Pull request closed without merging**
