### PR TITLE
Support argument forwarding after regular arguments

### LINKED ISSUE #1636: Leading argument with argument forwarding issue
## Overview

Hello. :wave: I'm currently running into an issue where Reek will stack dump. Luckily, it looks like Reek finishes its analysis but would be nice to resolve the stack dump.

## Steps to Recreate

I managed to narrow down the the issue to a simple code snippet:

``` ruby
# Save as `snippet.rb` and run as `reek snippet.rb`

class Demo
  def self.call(example, ...) = puts "TODO"
end
```

When you run the above as directed, you'll get the following stack dump:

<details>
  <summary>Full Details</summary>

``` 
Inspecting 1 file(s):
        !!!
        Source /Users/bkuhlmann/Engineering/Misc/snippet.rb cannot be processed by Reek.

        This is most likely a Reek bug.

        It would be great if you could report this back to the Reek team by opening a
        corresponding issue at https://github.com/troessner/reek/issues.

        Please make sure to include the source in question, the Reek version,
        and this entire error message, including the original exception below.

        Exception message:

        #<NoMethodError: undefined method `components' for s(:forward_arg):#<Class:0x000000010b07c4c8>

          children.flat_map(&:components)
                  ^^^^^^^^^>

        Original exception:

        /Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/ast/sexp_extensions/nested_assignables.rb:10:in `each'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/ast/sexp_extensions/nested_assignables.rb:10:in `flat_map'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/ast/sexp_extensions/nested_assignables.rb:10:in `components'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/ast/sexp_extensions/methods.rb:17:in `parameters'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/context/method_context.rb:53:in `default_assignments'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/smell_detectors/boolean_parameter.rb:25:in `sniff'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/smell_detectors/base_detector.rb:45:in `run'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/detector_repository.rb:44:in `block in examine'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/detector_repository.rb:42:in `each'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/detector_repository.rb:42:in `flat_map'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/detector_repository.rb:42:in `examine'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/examiner.rb:121:in `block in examine_tree'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/context/code_context.rb:56:in `each'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/context/code_context.rb:58:in `block in each'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/context/code_context.rb:57:in `each'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/context/code_context.rb:57:in `each'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/context/code_context.rb:58:in `block in each'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/context/code_context.rb:57:in `each'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/context/code_context.rb:57:in `each'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/examiner.rb:120:in `flat_map'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/examiner.rb:120:in `examine_tree'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/examiner.rb:94:in `block in run'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/examiner.rb:104:in `wrap_exceptions'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/examiner.rb:93:in `run'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/examiner.rb:61:in `smells'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/examiner.rb:77:in `smelly?'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/report/progress_formatter.rb:43:in `progress'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/report/text_report.rb:22:in `add_examiner'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/cli/command/report_command.rb:26:in `block in populate_reporter_with_smells'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/cli/command/report_command.rb:25:in `each'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/cli/command/report_command.rb:25:in `populate_reporter_with_smells'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/cli/command/report_command.rb:17:in `execute'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/lib/reek/cli/application.rb:32:in `execute'
	/Users/bkuhlmann/.cache/frum/versions/3.1.0/lib/ruby/gems/3.1.0/gems/reek-6.0.6/bin/reek:12:in `<top (required)>'
	/var/folders/9s/b1_9vxs16lv8bg0dqgn15g_h0000gn/T/frum_58720_1641744855711/bin/reek:25:in `load'
	/var/folders/9s/b1_9vxs16lv8bg0dqgn15g_h0000gn/T/frum_58720_1641744855711/bin/reek:25:in `<main>'

        !!!
```
</details>

If you remove the `example` argument from the code snippet, the problem will go away. For some reason, Reek doesn't like the positional parameter in addition to the argument forwarding syntax.

## Environment

- **Ruby**: ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [arm64-darwin21.2.0]
- **Reek**: 6.0.6

### PR DESCRIPTION
**Pull request by mvz**
Fixes #1636.

### CODE REVIEW

**Comment by troessner** [comment]
Nice, extensive spec coverage!

**Comment by bkuhlmann** [comment]
Matijs, thanks for fixing this! :bow: Out of curiosity, will a patch release be issued soon?

**Comment by mvz** [comment]
Since this adds support for a version of Ruby we didn't support previously this will be at least a minor release. @troessner wdyt, can we maybe merge #1619 and then release 6.1.0? The tooling (rubygems, bundler) should be good enough now to keep users of Ruby 2.4 and 2.5 from upgrading.

**Comment by troessner** [comment]
Agree, sounds like a good idea.

**Pull request merged**
