### PR TITLE
Handle encoding error when parsing the source

### LINKED ISSUE #1262: When erroring out because of an invalid byte-sequence, reek doesn't show what file it crashed on.
```
reek -ns

Inspecting 183 file(s):
SSSSSS....SS.....SSSS.S..SS.SSS..S./usr/local/bundle/gems/parser-2.4.0.0/lib/parser/source/buffer.rb:164:in `source=': invalid byte sequence in US-ASCII (EncodingError)
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:99:in `parse'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:33:in `initialize'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:50:in `new'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/source/source_code.rb:50:in `from'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/examiner.rb:40:in `initialize'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:26:in `new'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:26:in `block in populate_reporter_with_smells'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `each'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:25:in `populate_reporter_with_smells'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/command/report_command.rb:17:in `execute'
	from /usr/local/bundle/gems/reek-4.7.2/lib/reek/cli/application.rb:29:in `execute'
	from /usr/local/bundle/gems/reek-4.7.2/bin/reek:14:in `<top (required)>'
	from /usr/local/bundle/bin/reek:17:in `load'
	from /usr/local/bundle/bin/reek:17:in `<main>'
```

I would love it if reek told me what file it crashed on.

Anyway, thanks for all the hard work you do. Let me know if you need any info from me.

### PR DESCRIPTION
**Pull request by troessner**
Fixes #1262 - still wip though.

### CODE REVIEW

**Comment by troessner** [comment]
@mvz can you think of something to put [here](https://github.com/troessner/reek/pull/1263/files#diff-f63572ef48cf20a9eac97e84f1474209R44) so that I can trigger an EncodingError in our specs? If you have no idea as well then I'd go ahead and create a bad source file like describe [here](https://stackoverflow.com/questions/6374756/why-do-i-get-an-invalid-byte-sequence-in-utf-8-error-reading-a-text-file) and would use that one.

**Comment by mvz** [comment]
It may be hard to trigger that error because it may have to do with the locale set in the environment (see #1254).

How about using a double for the buffer and add a mock to have it raise some error? This would require some refactoring to be able to inject the buffer object, of course.

**Comment by troessner** [comment]
Hmmm, the specs fail with

>>
        expected Exception with message matching /Looks like bad source/, got #<RSpec::Mocks::MockExpectationError: #<Double (anonymous)> received unexpected message :source= with ("Code that raises an EncodingError")> with backtrace:
         # ./lib/reek/source/source_code.rb:100:in `parse'
         # ./lib/reek/source/source_code.rb:33:in `initialize'

Which is weird. I mean, obviously this line [here](https://github.com/troessner/reek/pull/1263/files#diff-f9dae46a54ebb72c2c734ff15d80d26eR99):

```Ruby
buffer = Parser::Source::Buffer.new(origin, 1)
```

returns the proper which I have instructed to accept the "source" as method call via 

```Ruby
allow(buffer).to receive(:source) { raise EncodingError }
```

Not really sure what's going on here. @mvz do you have any idea?

**Comment by mvz** [comment]
It turns out you need  to stub `:source=` instead of `:source`.

**Comment by troessner** [comment]
Haha, what a stupid mistake of me, thanks for the hint.
I am in lovely Marocco for the next 3 weeks without laptop, could you possibly finish this one?

**Comment by mvz** [comment]
Sure!

**Comment by mvz** [comment]
I'm not entirely sure about this solution anymore (I know, I proposed it 😞). I thought we could do something like we do in `Examiner`, but `Examiner` actually does something quite complicated: It catches all exceptions and then either prints stuff or re-raises. We should definitely not do that in `SourceCode` as well. Ideally, we would catch errors in `SourceCode#parse` in `Examiner#run`, but in fact it is already executed inside `Examiner#initialize`. If we can delay calling `#parse` until either `#valid_syntax?` or `#syntax_tree` is called, that problem would be solved. That way, all tricky code runs inside `Examiner#run`, and we can just modify that to catch all errors happening inside it.

**Comment by mvz** [comment]
I've updated Examiner to handle these errors properly during `#run`.

Because of #1254 I think we cannot yet say the encoding error needs to be fixed by the user.

**Comment by troessner** [comment]
Very nice. Looks good to me. Wanna squash?

**Comment by mvz** [comment]
I'll see if I can make Travis behave.

**Comment by mvz** [comment]
Squashed and green.

**Pull request merged**
