### PR TITLE
Allow longer timeout for debugging purposes

### PR DESCRIPTION
**Pull request by mvz**
Stops specs from failing while debugging with pry.

### CODE REVIEW

**Comment by troessner** [comment]
I ran into the same problem but this solution feels very hacky.
How about using a CLI flag:

```DEBUG=1 bundle exec rspec spec/.....```

and then doing:

```Ruby
Timeout.timeout(5, &example) unless ENV['DEBUG']
```

wdyt?

**Comment by mvz** [comment]
Yeah, that is much nicer!

**Comment by troessner** [comment]
Great! And let's also not forget to document this [here](https://github.com/troessner/reek#developing-reek--contributing) (we should mention the 5 seconds there anyways, regardless of this PR)

**Comment by backus** [comment]
Could also put something like this at the top of your spec_helper:

```ruby
source =
  Pathname
    .glob('**/*.rb')
    .map(&:read)
    .join

DEBUG_MODE = (source =~ /binding\.pry/)
```

**Comment by troessner** [comment]
@backus super smart solution but i think a too little smart for my taste for sth mundane like this ;)

**Comment by troessner** [comment]
I think #969 is the way to go

**Comment by backus** [comment]
@troessner alright. If you don't mind I'm curious what specifically you mean. Do you mean that the presence of a `binding.pry` disabling the timeout is too magic for something like this? I understand the judgement call I just want to make sure I understand your motivations.

For context, I have a test timeout setup (for mutant) in some of my projects and I've been meaning to add something like this `binding.pry` solution.

**Comment by troessner** [comment]
@backus dont get me wrong, i really like your solution. It is just that I'd prefer something more explicit to avoid confusion (e.g. for new team members).
But thats really just a slight preference, if the other team members prefer your idea i am happy to roll with it as well.

**Comment by backus** [comment]
@troessner okie doke. I was just curious. Wasn't trying to apply any pressure for you to take my solution. I don't even contribute to reek (yet). I just watch this repo because it is interesting and I think you guys are good developers :smile:

**Comment by troessner** [comment]
>> Wasn't trying to apply any pressure for you to take my solution. 

Wasn't even remotely perceived like that. Was just a regular discussion - we absolutely appreciate those kind of suggestions :)

**Comment by troessner** [comment]
Closing this one with #969 merged.

**Pull request closed without merging**
