### PR TITLE
Add a progress formatter to the text report

### PR DESCRIPTION
**Pull request by jhubert**
This is a revision of #983 that includes a progress formatter that can be extended in the future. As part of the work to get the specs to pass, there a few things I found irritating about the other implementation. 

Submitting this as a hopeful for being able to finally merge this in and close out the issue.

### CODE REVIEW

**Comment by troessner** [comment]
This looks great!

2 small things left to do:

1.) Squash to one commit
2.) Make this PR point to the "reek-5" branch (since this will probably break a lot of plugin integrations)

Then I'll happily merge! (And afterwards we need to talk about when to release Reek 5)

**Comment by jhubert** [comment]
Squashed to one commit but the `reek-5` branch seems to be a fair bit behind the master branch. Is that expected?

**Comment by troessner** [comment]
Yeah, he's behind a bit because our Reek-5 discussion got stalled.  Shouldnt be a problem though, i'll update it later, just go ahead ;)

**Comment by troessner** [comment]
>> I can re-do it for the reek-5 branch, just want to make sure before I start the work.

Ah, missed that! On the road atm,  i'll update the branch tonight, please hold on.

**Comment by troessner** [comment]
I just rebased the reek-5 branch with master, you're good to go ;)

**Comment by jhubert** [comment]
Replaced by #1100

**Pull request closed without merging**
