### PR TITLE
Switch all local requires to require_relative

### PR DESCRIPTION
**Pull request by chastell**
At least a stepping stone towards fixing https://github.com/troessner/reek/issues/406.

### CODE REVIEW

**Comment by troessner** [comment]
Reviewed and in favor of this. While this is certainly a lot more verbose it also is a lot clearer, at least in my mind.
@mvz what do you think?

**Comment by chastell** [comment]
_puts his thought leadership cap on_

I think most of the verbosity stems from two things: high coupling (many `require_relative` lines in classes that need a lot of other classes to work) and class hierarchy not matching usage (the longish `../..` parts of the relative paths). Both are things to be gradually fixed, but this diff is their symptom, not a problem with `require_relative` itself.

**Comment by troessner** [comment]
>> I think most of the verbosity stems from two things: high coupling (many require_relative lines in classes that need a lot of other classes to work) and class hierarchy not matching usage/dependencies (the longish ../.. parts of the relative paths). Both are things to be gradually fixed, but this diff is their symptom, not a problem with require_relative itself.

Yes, couldn't agree more!
We already removed a lot of unnecessary requires in the last months but I think there are still quite many left that could be removed or where the class hierarchy should be changed - but this would be a different PR like you already noted as well.

**Comment by mvz** [comment]
I'll have a look at this later in the week or this weekend.

**Comment by mvz** [comment]
Sorry, I didn't manage to take a look at this yet. Hope you can hold on a little longer ...

Just FYI, my current thinking is:
* The Ruby ecosystem should handle which version of a gem gets loaded, by using `require_relative` we're circumventing that.
* This is a workaround for a problem that only occurs if you're developing reek **and** you have rubygems-bundler installed.
* I don't see *any* guarantee in the code of rubygems that going to `../lib/` from inside `bin/` will get you to the `lib` part of the same gem (I think this is the most dangerous part of this change).

**Comment by chastell** [comment]
> The Ruby ecosystem should handle which version of a gem gets loaded, by using `require_relative` we're circumventing that.

I believe that the given `bin/reek` executable should always load its related reek files. RubyGems take care of _which_ `bin/reek` executable gets run (`$GEM_HOME/bin/reek` is a thin wrapper that does exactly this dispatch), but once the given `bin/reek` executable is run it should load _its_ related files, and that’s exactly what `require_relative` does.

The same goes for `require 'reek'` done by a third party (i.e., using reek as a library) – RubyGems take care of which `lib/reek.rb` gets required, but _that_ file should always load its related implementation.

> This is a workaround for a problem that only occurs if you're developing reek **and** you have rubygems-bundler installed.

I think this is unrelated to rubygems-bundler (and I don’t think it’s a workaround) – and, anyway, rubygems-bundler’s behaviour should be exactly the same as pure RubyGems’ with `RUBYGEMS_GEMDEPS` set to `-` (currently RubyGems’ `Gemfile` parsing is lacking, so it blows up in reek’s case, but it’s the same in principle and will work the same as soon as RubyGems’ `Gemfile` parsing gets better).

> I don't see _any_ guarantee in the code of rubygems that going to `../lib/` from inside `bin/` will get you to the `lib` part of the same gem

I don’t understand. RubyGems’ executable wrapper (at `$GEM_HOME/bin/reek`) runs the right `bin/reek` by doing `load Gem.bin_path('reek', 'reek', version)` (once the right `version` is computed) – and it’s pure Ruby that makes sure that a `require_relative` inside _that_ `load`ed `bin/reek` finds _its_ `../lib`. If that wasn’t guaranteed then there would be a Ruby bug (`require_relative` is always relative to `__FILE__`, it doesn’t care about the current directory or the original/top-level `load`/`require` call).

**Comment by troessner** [comment]
I agree with everything @chastell said. 
Especially:

>> I believe that the given bin/reek executable should always load its related reek files. RubyGems take care of which bin/reek executable gets run ($GEM_HOME/bin/reek is a thin wrapper that does exactly this dispatch), but once the given bin/reek executable is run it should load its related files, and that’s exactly what require_relative does.
The same goes for require 'reek' done by a third party (i.e., using reek as a library) – RubyGems take care of which lib/reek.rb gets required, but that file should always load its related implementation.

**Comment by troessner** [comment]
And I think things like that were part of the reason why "require_relative" was invented in the first place. I think using "require" for all the things is as common as it is misplaced.

**Comment by troessner** [comment]
Sooooo, what do we do here? Seems like we're in a dead end here.
Should we take a democratic vote?.;)

**Comment by mvz** [comment]
I'm convinced now that this is in general a good thing, especially because of this:

> RubyGems take care of which `lib/reek.rb` gets required, but that file should always load its related implementation.

So, :+1: on loading related files from `lib/reek.rb` using `require_relative`.

I have one remaining worry, which is that `bin` and `lib` may not be guaranteed by ruygems to be sister directories (at least, looking at the implementation). However, this seems to be generally assumed, so let's assume this as well.

One nice thing about this change is that checking out reek and running straight `bin/reek` will use the correct libraries.

Conclusion: :shipit:

**Comment by troessner** [comment]
Great, merged!

**Pull request merged**
