### PR TITLE
Remove unneeded gender reference to a method

### PR DESCRIPTION
**Pull request by tibbon**
Methods don't have genders, so I'm proposing removing the reference to it as `her`.

### CODE REVIEW

**Comment by mikegee** [comment]
Unfortunately, "Prima Donna" remains gendered. So maybe we should change the name of the whole smell?

**Comment by tibbon** [comment]
I agree, the smell name overall is highly gendered and I figured that was a larger conversation.

If we do want to address that, it might be better in another PR, but a few suggestions for a better smell name:

- **Unmatched Mutate Method**
- **False Mutate Method** (Not all methods without `!` are free of side effects)
- **Celebrity Method** 
- **False Warning Method**
- **Uncertain Danger Method**
- **Whiz-bang Method** (has a neat whimsy, and points to the fact that there's a `!` in the offending method)
- **Alternate Method**
- **Scary Method**

**Comment by mvz** [comment]
Hey @tibbon, thanks for your patch. I definitely agree with the proposed change to the wording. I'll leave this unmerged for a bit so we have a place to discuss a possible new name for this smell.

**Comment by troessner** [comment]
I'm fine with changing this as well. I like whiz-bang :)

**Comment by troessner** [comment]
>> I like "whiz bang" too, but this may also be a good opportunity to change the name to something descriptive

I believe it is quite descriptive :)

**Comment by mvz** [comment]
(As an aside, it seems the term "prima donna" can, in the English language, refer to both men and women, so its use here is not so strange. I still don't like the smell name very much, since it's not very descriptive.)

**Comment by mvz** [comment]
> I believe it is quite descriptive :)

Well, it mentions 'bang', I'll grant you that :stuck_out_tongue:.

**Comment by mikegee** [comment]
"Missing Safe Method"?

**Comment by mvz** [comment]
@mikegee nice. It reverses the naming logic: Instead of naming what is there, it names what is, well, missing.

**Comment by tibbon** [comment]
I agree "Missing Safe Method" is quite descriptive.

**Comment by troessner** [comment]
>> Along that line, I'd suggest SelfImportantMethod, but there might be potential confusion with keyword self

Yep, that would be problematic probably :)

I think we should go with "Missing Safe Method".

>> If a decision to change the name is made, I'd be happy to make an additional commit for that.

That would be great @tibbon - I'd probably would be better though if it was a new pull request since now the scope has changed significantly from a fix patch to a minor version update including a different branch name (I'd suggest "change-PrimaDonnaMethod-to-MissingSafeMethod").

**Comment by mvz** [comment]
> I'd probably would be better though if it was a new pull request

Agreed. Let's merge this one first.

**Pull request merged**
