### PR TITLE
Added Checkstyle format XML report support

### PR DESCRIPTION
**Pull request by sauliusgrigaitis**
Added Checkstyle XML report support. We use it with Jenkins Violations plugin.

### CODE REVIEW

**Comment by mvz** [comment]
Hi @sauliusgrigaitis, thanks for your contribution. Can you provide some pointers to what Checkstyle XML is? I've never heard of it.

**Comment by sauliusgrigaitis** [comment]
Hi @mvz , http://checkstyle.sourceforge.net/ . A lot of violations visualization tools ( like https://wiki.jenkins-ci.org/display/JENKINS/Violations ) support Checkstyle format XML files, so for compatibility reasons it would be great to have such Checkstyle format XML for reek.

**Comment by mvz** [comment]
Thanks @sauliusgrigaitis.

**Comment by mvz** [comment]
@sauliusgrigaitis can you create a separate branch for this feature? It helps with rebasing and merging and will stop GitHub from adding any new commits on your master branch to the pull request.

**Comment by troessner** [comment]
@sauliusgrigaitis and please point that branch to "develop", not "master" since we're following gitflow since 3,5 hours.:)

**Comment by troessner** [comment]
Closing this one in favor of #450

**Pull request closed without merging**
