### PR TITLE
Added missing require_relative

### PR DESCRIPTION
**Pull request by sauliusgrigaitis**

### CODE REVIEW

**Comment by troessner** [comment]
Why is this missing? In what situation is this raising an error?

**Comment by sauliusgrigaitis** [comment]
It raises error when trying to use SmellRepository externally.

```
/home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-d3c4f95b58d1/lib/reek/core/smell_repository.rb:22:in `initialize': uninitialized constant Reek::Core::SmellRepository::Configuration (NameError)
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-d3c4f95b58d1/lib/reek/examiner.rb:62:in `new'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-d3c4f95b58d1/lib/reek/examiner.rb:62:in `block in run'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-d3c4f95b58d1/lib/reek/source/source_repository.rb:40:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-d3c4f95b58d1/lib/reek/source/source_repository.rb:40:in `each'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-d3c4f95b58d1/lib/reek/examiner.rb:61:in `run'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-d3c4f95b58d1/lib/reek/examiner.rb:32:in `initialize'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/lib/rubocop/git/style_guide.rb:14:in `new'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/lib/rubocop/git/style_guide.rb:14:in `violations'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/lib/rubocop/git/style_checker.rb:26:in `offenses'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/lib/rubocop/git/style_checker.rb:16:in `block in violations'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/lib/rubocop/git/style_checker.rb:15:in `map'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/lib/rubocop/git/style_checker.rb:15:in `violations'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/lib/rubocop/git/runner.rb:21:in `violations'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/lib/rubocop/git/runner.rb:51:in `display_violations'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/lib/rubocop/git/runner.rb:13:in `run'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/lib/rubocop/git/cli.rb:10:in `run'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bundler/gems/reek-git-41ac71f71bf5/bin/reek-git:5:in `<top (required)>'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bin/reek-git:23:in `load'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bin/reek-git:23:in `<main>'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/saulius/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```
More peeps faced it https://github.com/pocket-playlab/optimus-prime/issues/38 , but I can do that ```require``` on my end if you don't agree with this patch.

**Comment by mvz** [comment]
@sauliusgrigaitis please see #417.

**Comment by troessner** [comment]
@sauliusgrigaitis reek 2.1.0 has been released, please upgrade, closing this.

**Comment by sauliusgrigaitis** [comment]
@troessner thanks!

**Pull request closed without merging**
