### PR TITLE
Remove ruby management related files

### PR DESCRIPTION
**Pull request by bruno-**
Some people might prefer rbenv so `.ruby-gemset` file only creates noise for them.

The person actually using the `.ruby-gemset` file should probably gitignore it globally from `~/.gitignore`.

### CODE REVIEW

**Comment by chastell** [comment]
I switched from RVM to ruby-install + chruby, so I’m for this change, but I’d love to have @troessner’s / @mvz’s input before merging.

**Comment by mvz** [comment]
I'm all for removing this file, since I don't use it.

**Comment by andyw8** [comment]
+1

It should be up to the RVM user to decide which gemset to use when working on a project.

**Comment by troessner** [comment]
Thx!

**Pull request merged**
