### PR TITLE
Bump version to 4.0.0.

### PR DESCRIPTION
**Pull request by troessner**

### CODE REVIEW

**Comment by troessner** [comment]
Normally I'd merge those "bump" PR's myself but in this case we should all agree on it.
@mvz do you still want to check out our open tickets before merging / releasing?

**Comment by mvz** [comment]
Yup, shouldn't take long.

**Comment by mvz** [comment]
Reek 4 is ready to go as far as I'm concerned.

**Comment by troessner** [comment]
And released it is!

**Comment by mvz** [comment]
\o/

**Pull request merged**
