### PR TITLE
Provide default value for public_methods_only for UtilityFunction

### PR DESCRIPTION
**Pull request by mvz**

### CODE REVIEW

**Comment by troessner** [comment]
Code looks good, but `Mutant` is not so enthused about this change 😆

**Comment by mvz** [comment]
Yes :cry:. The tests I added in this PR kill most of those mutations. However, when I look in the list of tests run by Mutant on Travis those tests are not included.

**Comment by mvz** [comment]
I squashed the commits. Merge?

**Comment by troessner** [comment]
Merged! Any idea what we can do about:

>> However, when I look in the list of tests run by Mutant on Travis those tests are not included.

?

**Comment by mvz** [comment]
> Any idea

Not really. I have a feeling there may be some issues with the `--since` flag due to how Travis checks out the repo. See also the build failures on #931.

**Pull request merged**
