### PR TITLE
Hotfix: Handle array decomposition

### LINKED ISSUE #502: Reek fails on methods with unpacked parameters – undefined method `optional_argument?' for (mlhs (NoMethodError) ...
Hi,

See [official Ruby documentation](http://ruby-doc.org/core-2.2.0/doc/syntax/methods_rdoc.html#label-Array+Decomposition) for why this syntax is valid.

To reproduce the failure:
```
cat <<-EOF > test.rb
def meth(param1, (param2_a, param2_b))
  puts param1, param2_a, param2_b
end
meth('1', ['2_a', '2_b'])
EOF

ruby test.rb
reek test.rb
```

The output on my workstation (Ruby `2.2.1`, Reek `2.1.0`):
```
$ cat <<-EOF > test.rb
> def meth(param1, (param2_a, param2_b))
>   puts param1, param2_a, param2_b
> end
> meth('1', ['2_a', '2_b'])
> EOF
$ 
$ ruby test.rb
1
2_a
2_b
$ reek test.rb
/home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/method_context.rb:13:in `block in default_assignments': undefined method `optional_argument?' for (mlhs (NoMethodError)
  (arg :param2_a)
  (arg :param2_b)):#<Class:0x00000001ed49e0>
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/method_context.rb:12:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/method_context.rb:12:in `default_assignments'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/smells/boolean_parameter.rb:25:in `examine_context'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/smells/smell_detector.rb:92:in `examine'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/smell_repository.rb:36:in `block in examine'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/smell_repository.rb:35:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/smell_repository.rb:35:in `examine'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:169:in `check_smells'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:163:in `block in inside_new_context'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:175:in `push'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:161:in `inside_new_context'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:45:in `process_def'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:23:in `process'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:32:in `block in process_default'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:31:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:31:in `process_default'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:97:in `process_begin'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/core/tree_walker.rb:23:in `process'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/examiner.rb:64:in `block in run'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/source/source_repository.rb:40:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/source/source_repository.rb:40:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/examiner.rb:61:in `run'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/examiner.rb:32:in `initialize'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/cli/reek_command.rb:13:in `new'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/cli/reek_command.rb:13:in `block in execute'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/cli/reek_command.rb:12:in `each'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/cli/reek_command.rb:12:in `execute'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/lib/reek/cli/application.rb:32:in `execute'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/gems/reek-2.1.0/bin/reek:11:in `<top (required)>'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/bin/reek:23:in `load'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/bin/reek:23:in `<main>'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/bin/ruby_executable_hooks:15:in `eval'
        from /home/amir/.rvm/gems/ruby-2.2.1@rubycritic/bin/ruby_executable_hooks:15:in `<main>'
```

Thanks for taking the time to look into this.

Yours,
Amir

### PR DESCRIPTION
**Pull request by mvz**
Fixes #502.

Basing this off master as it's a bug fix.

### CODE REVIEW

**Comment by chastell** [comment]
:+1: – but I’m not sure what’s the policy regarding version bumps; do we want to do the bump in (one of) the hotfixes for a given release, or do we plan to have a separate patch release for every hotfix?

**Comment by troessner** [comment]
I dont think this should be branched of master. How about a "regular" patch release?

**Comment by mvz** [comment]
Yeah, I tried to understand GitFlow's position on this, and as I understood it, it handles bug fix releases via a hotfix branch from master, and each hotfix includes a patch version bump. This is also what the gitflow tool urges you to do once you start a hotfix branch.

Doing a 'regular' patch release off of `develop` makes it difficult to ensure it will not contain any changes that warrant a minor version bump.

In general, I prefer doing tiny patch releases in order to get them out the door as soon as possible.

**Comment by troessner** [comment]
>> Yeah, I tried to understand GitFlow's position on this, and as I understood it, it handles bug fix releases via a hotfix branch from master, and each hotfix includes a patch version bump. This is also what the gitflow tool urges you to do once you start a hotfix branch.
Doing a 'regular' patch release off of develop makes it difficult to ensure it will not contain any changes that warrant a minor version bump.

Agreed and merged this bad boy.:)
@mvz please go ahead and update "develop" / release-branch.

**Comment by mvz** [comment]
@troessner I think you need to check out master and do `bundle exec rake release` there. I'll merge master into develop.

**Comment by troessner** [comment]
>> @troessner I think you need to check out master and do bundle exec rake release there.

Just did that.
What I also just did:

>> gem owner reek -a matijs@matijs.net 
gem owner reek -a chastell@chastell.net

;)

**Comment by mvz** [comment]
> gem owner reek -a matijs@matijs.net 

Thanks!

**Comment by chastell** [comment]
> gem owner reek -a chastell@chastell.net

Oh wow, thanks, much appreciated! \o/

**Pull request merged**
