### PR TITLE
Allow parser version 2.7

### PR DESCRIPTION
**Pull request by mvz**

### CODE REVIEW

**Comment by troessner** [comment]
Looks good to me, feel free to merge once CI is green ;)

**Comment by jgarber623** [comment]
Thanks for this update, @mvz and @troessner! When might a new version of the gem be released with this change?

**Comment by mvz** [comment]
Ah yes, it's about time :slightly_smiling_face:

**Comment by troessner** [comment]
@mvz i am on vacation without laptop, can you take this over?

**Comment by mvz** [comment]
Sure, I'll take care of it.

**Comment by mvz** [comment]
@jgarber623 Released as 5.6.0 :tada:

**Comment by jgarber623** [comment]
@mvz Awesome, thank you!

**Pull request merged**
