### PR TITLE
Print exception classes

### PR DESCRIPTION
**Pull request by mvz**
#1265.

### CODE REVIEW

**Comment by chastell** [comment]
This looks good to me, but needs either some `:reek:` whitelisting or refactoring _and_ a rebase.

**Comment by troessner** [comment]
>> This looks good to me

@chastell but it still says WIP ;)

**Comment by mvz** [comment]
Definitely WIP 😆

**Comment by chastell** [comment]
Yeah, sorry, got tricked by the
> mvz changed the title from [WIP] Print exception classes to Print exception classes 22 days ago
part. 😛

**Comment by mvz** [comment]
Ready for review now.

**Comment by chastell** [comment]
:+1: – I love the much shorter and to-the-point message and the general small clean-up of the code.

**Comment by troessner** [comment]
Very nice, merged!

**Pull request merged**
