### PR TITLE
Increase rubocop's line length limit.

### PR DESCRIPTION
**Pull request by troessner**
I'm sorry, but 100 characters max is driving me CRAZY.
Can we please use 120, pretty please?

### CODE REVIEW

**Comment by chastell** [comment]
Don’t look at me, I’m an 80-character-max person myself. But I won’t block this one – if it can’t be 80 it can as well be 120… :stuck_out_tongue:

**Comment by mvz** [comment]
Sure, on two conditions:
* No complaints when I mercilessly line-wrap to 80 characters :smile:.
* Please also update the comment for this setting :laughing:.

**Comment by troessner** [comment]
>> No complaints when I mercilessly line-wrap to 80 characters :smile:.

Ack!

>> Please also update the comment for this setting :laughing:.

Done ;)

**Comment by mvz** [comment]
Awesome! Merging ...

**Comment by chastell** [comment]
>> No complaints when I mercilessly line-wrap to 80 characters :smile:.

> Ack!

Oh on that condition I’ll even merge it! :metal:

**Comment by chastell** [comment]
Oh. :)

**Pull request merged**
